server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

spring:
  config:
    use-legacy-processing: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

    hibernate:
      ddl-auto: create-drop
    open-in-view: true

  profiles:
    include:
      - jwt
      - oauth

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  output:
    ansi:
      enabled: always

  redis:
    port: 6379
    host: localhost
